### ISSUE TITLE
official project name: neko or nekovm?

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/neko#100]
Just want to confirm the official project name is neko (not nekovm).

I'm asking because during [submission](https://build.opensuse.org/request/show/345882) of the neko package to openSUSE, the reviewer asked if neko is a more appropriate name for the package. The openSUSE package, when it was created and added into the openSUSE game project, was named nekovm.

The [Fedora package](https://admin.fedoraproject.org/pkgdb/package/nekovm/) is also named nekovm. And our official neko website also has the domain nekovm.org. However, the [Debian package](https://packages.debian.org/sid/neko) is indeed named just neko. And we usually just call it neko.

I guess in the end it is not very important how the package is named. But still, it is good to know when we mention the "neko thing", should we call it neko or nekovm or whatever. Kind of a branding decision.

**Comment by Simn** [comment]
From my understanding neko is the language and nekovm is what runs the language. It might make sense to focus on nekovm because it's a name that should be available almost everywhere.

**Comment by andyli** [comment]
That's reasonable. If we want to change to nekovm, we better change the github repo name, as well as the files in the [download page](http://nekovm.org/download) (e.g. neko-2.0.0.tar.gz => nekovm-2.0.0.tar.gz). Of course we can delay it to the next neko release.

**Comment by ppenzin** [comment]
I thought that it was supposed to be "neko", so I called the pending FreeBSD package [the same](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=204664).

Do package names have to be the same everywhere? Packages for the Boehm Garbage Collector are named wildly differently on different platforms, for example ;)

**Comment by andyli** [comment]
It is mostly a branding matter for our side. For the distros' side, most of them have packaging guideline detailing how things should be named. But of course usually the advice is just to use the upstream name.

@ncannasse Would you make a quick decision here such that I can finalize the openSUSE package ;)

**Comment by ncannasse** [comment]
The official project name is Neko, NekoVM.org is because neko.org/net/com were not available. You can however name the package either neko or nekovm, both makes sense.

**Comment by andyli** [comment]
Ok! Thanks for the answer!
