### ISSUE TITLE
removing the use of make on Windows

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/neko#103]
I would like to remove the use of make on Windows (Visual Studio).
The only usages of make I can find are in neko.vc(x)proj / nekoml.vc(x)proj. But from the AppVeyor log, I can see that they in fact do nothing: 
```
make: Nothing to be done for `neko'.
make: Nothing to be done for `nekoml'
```
And indeed the build succeed even if I removed the two projects from the VS solution: https://ci.appveyor.com/project/andyli/neko/build/28

So, the question is, can I simply remove the 2 projects?

**Comment by ncannasse** [comment]
Could you tell me which usage of make is done on Windows (where it's triggered)?

**Comment by andyli** [comment]
In src/neko.vc(x)proj:
 * make neko / make clean neko / make clean
In src/nekoml.vc(x)proj:
 * make nekoml / make clean nekoml / make nekoml

**Comment by ncannasse** [comment]
Ah, these are necesssary to rebuild neko/nekoml bootstrap. It's not necessary to build them since they are already precompiled in boot directory.

**Comment by andyli** [comment]
I will just leave the project files there, but I skipped building those in ec97f8c0f5a338320ab9f4974a4c8d86ac4cb8c1
