### ISSUE TITLE
"nekotools boot" on Ubuntu 14 x64:The bootable executable file was not found : neko

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/neko#110]
I download neko from github, run `make install` and try to convert my `test.n` into executable:
```shell
nekotools boot test.n
# result:
Neko_error(The bootable executable file was not found : neko)
```
Looks like we need to make a copy of the neko in the /usr/lib/neko:
```shell
cp /usr/bin/neko /usr/lib/neko/
```
This fix the problem. I think, we must have to do this in Makefile/install (if it is not only my problem).

**Comment by ncannasse** [comment]
@andyli this might have something to do with "make install" changes, maybe?

**Comment by ncannasse** [comment]
(nekotools is reading `neko` binary from `NEKOPATH`, which includes `/usr/lib/neko` by default)

**Comment by andyli** [comment]
Indeed. But `neko` really shouldn't be placed in `/usr/lib`. Can I modify `nekotools` to look for `neko` in `$PATH` with `/usr/lib/neko` as fallback?

**Comment by andyli** [comment]
I mean with `NEKOPATH` as fallback.
