### ISSUE TITLE
Relational Operators (>, <, >=, <= etc.) should always produce false with NaN

### ISSUE THREAD

**Issue by NekR** [HaxeFoundation/neko#111]
I am not a user of Neko and do not know its syntax and details, so please check for issue details here: https://github.com/HaxeFoundation/haxe/issues/4776

**Comment by Simn** [comment]
I can't find the commit, but my tests suggest that this has already been fixed.

**Comment by Simn** [comment]
Found the commit after all: https://github.com/HaxeFoundation/neko/commit/90b23bec4270f2cf5355df34b3109692a3215435
