### ISSUE TITLE
Haxe snapshot build on the PPA is missing ssl.ndll

### ISSUE THREAD

**Issue by jonasmalacofilho** [HaxeFoundation/neko#123]
Current neko snapshots (`neko-2.0.0+1SNAPSHOT20160406143259+3801953-1~ubuntu15.10.1~ppa1`) are missing the new `ssl.ndll`.

Most likely, the server is simply missing a copy of mbedTLS.

**Comment by andyli** [comment]
It should contain ssl.ndll now.
