### ISSUE TITLE
update Boehm GC

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/neko#126]
Compiling with the latest Boehm GC (7.4.2), Neko crashes in run-time on Windows. Neko works fine on Mac and Linux, although there are a number of deprecation warnings.

Just logging it here for now. It would be great if there is anyone who want to contribute.

**Comment by ppenzin** [comment]
I am thinking of trying to build Neko on Windows (duh) to check something. Can look at this while I am at it, though not sure how easy it will be to fix. Do you know if it started failing with 7.4.2 or earlier? I am at 7.6.0 on -BSD

**Comment by andyli** [comment]
If I remember correctly, Neko on Windows doesn't work with any Boehm GC version higher then 7.1.

**Comment by andyli** [comment]
Just used `git bisect` and found out https://github.com/ivmai/bdwgc/commit/68d2cdac0c33d700333fea4379d7cb211ccfd586 is the breaking commit.

**Comment by andyli** [comment]
Somehow https://github.com/HaxeFoundation/neko/commit/7c53e41b6831590c3a4bd55b698870aa251059ef fixed the issue...
