### ISSUE TITLE
Is fopen(path, "x"); supported?

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/neko#132]
I tried to write the following haxe code but it seems not working. It throws an error which is `trace`d as `[file_open,myfile.txt]`

```haxe
static var file_open = neko.Lib.load("std","file_open",2);
file_open(untyped "myfile.txt".__s, untyped 'x'.__s);
```

**Comment by ncannasse** [comment]
Most likely the file does not exists or can't be read.

**Comment by mwgamera** [comment]
Let me just note that plain `x` without `r` or `w` or whatever, shall fail with an invalid argument error before even trying to open the file. Though, neko doesn't check errno so it won't tell you that.
Also, it's a non-portable glibc extension, but neko does support here everything your C library does.

**Comment by kevinresol** [comment]
@mwgamera Thanks for the information. Didn't know that 'x' has to be used with 'r' or 'w'.
