### ISSUE TITLE
CMake broken with MSVC 2015

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/neko#133]
When using MSVC Community 2015, Neko is not able to compile because the BoehmGC project fails to compile in math.h because of a syntax error in `_Check_return_`

I guess this is why all the other things fails to compile afterwards as well.

**Comment by andyli** [comment]
Yeah... it will probably be solved once boehmgc is updated (https://github.com/HaxeFoundation/neko/issues/126).

**Comment by andyli** [comment]
fixed
