### ISSUE TITLE
Exception stacktrace in non-main thread

### ISSUE THREAD

**Issue by Yanrishatum** [HaxeFoundation/neko#134]
When exception occurs in non-main thread Neko don't print it.

Simple reproduction:
```haxe
package;
import neko.Lib;
import neko.vm.Thread;

class Main 
{
  static function main() 
  {
    Thread.create(smain);
    
    throw "Exception in main thread";
  }
  
  static function smain():Void
  {
    throw "Exception in non-main thread";
  }
}
```
`haxe -main Main -cp . -neko threadException.n -debug`
Output is (order of text may vary depending on PC):
```
An exception occured in a neko Thread :
Called from neko.vm.Thread::$statics line 1
Called from Main::main line 11
Uncaught exception - Exception in main thread
Exception in non-main thread
```
There should be 2 exception stacktraces for main thread and non-main thread, but there's only one from main thread + exception text from non-main thread.

**Comment by Yanrishatum** [comment]
OS check:
Windows 7: Same output as provided above.
Mac OS X El Capitan 10.11.5: Same output output as provided above.
Ubuntu on virtual machine: Exception text from non-main thread does not printed at all. Output:
```
neko threadException.n
Called from neko.vm.Thread::$statics line 1
Called from Main::main line 11
Uncaught exception - Exception in main thread
```

**Comment by ncannasse** [comment]
The problem here is that the program will exit before all threads are terminated. If you want to make sure this does not happen, use a custom API that will wait for all threads before exit, and catch their exceptions.
