### ISSUE TITLE
[OSX 10.11.2] Uncaught exception - std@module_read

### ISSUE THREAD

**Issue by man2** [HaxeFoundation/neko#135]
I got this:
Uncaught exception - std@module_read

when trying to run my neko program using openfl / lime test neko on my mac osx 10.11.2

**Comment by ibilon** [comment]
Openfl ships an outdated mac neko binary that doesn't have the size fix.
I'll use the new neko release binaries to update openfl.

**Comment by man2** [comment]
I'm using nekoVM 2.1.0
Is it outdated version? Which version should I get?

**Comment by man2** [comment]
It's problem with openfl Lime using older version of Neko, I'm closing this
