### ISSUE TITLE
socket issue

### ISSUE THREAD

**Issue by codeservice** [HaxeFoundation/neko#139]
On neko 2.1.0, haxe 3.2 socket thread server not working. Hang on code: sock.accept()
In old neko and cpp it was fine.

**Comment by ncannasse** [comment]
I'm not sure what you mean here. It's normal to block in accept() until a socket is connected to the server. You need to have bind() and listen() before it.

**Comment by codeservice** [comment]
Sure I do. I am talking about few haxe web servers on git-hub broken now on
new neko. It was working on old neko and still working for cpp targets. I
spent time looking for issue and find out thast new neko hanging on socket
accept() method. Check for example https://github.com/tong/wtri

**Comment by ncannasse** [comment]
accept() implemention has not been changed in years so I suggest you might have some problem with security on your computer, which does not allow the new neko binary to open the socket.

**Comment by codeservice** [comment]
strange. new neko has all admin roles on windows, same as old. I have this
issue on Mac too.
