### ISSUE TITLE
Uncaught exception - load.c(237) : Failed to load library : C:\HaxeToolkit\neko/fcgi.ndll

### ISSUE THREAD

**Issue by ovidiugabriel** [HaxeFoundation/neko#145]
Hello,

I am trying to load fcgi library  https://github.com/TheHippo/hxfcgi into a neko program

```
var p = $loader.loadprim("fcgi@hxfcgi_create_request", 0);
$print( p() );
```

When I run this I get:

```
Called from testprim.neko line 1
Uncaught exception - load.c(237) : Failed to load library : C:\HaxeToolkit\neko/fcgi.ndll
```

The fcgi.ndll file is there but the correct path is AFAIK **c:\HaxeToolkit\neko\fcgi.ndll**
I am running on windows 10 with NekoVM 2.1.0

**Comment by ovidiugabriel** [comment]
The same happens for the similar HAXE code:

```haxe
return untyped __global__.__loadprim("fcgi", "hxfcgi_create_request", 0);
```

But this time I get a less concludent error message, running in HXCPP target:

```
Web.hx:330: load(hxfcgi_create_request, 0)
Lib.hx:30: load(fcgi, hxfcgi_create_request, 0)
Web.hx:337: Could not load module fcgi@hxfcgi_create_request__0
```

**Comment by ovidiugabriel** [comment]
Hello, do we have any update on this? I happened only in my case?

**Comment by ncannasse** [comment]
Most likely another DLL is required for HxFCGI, please ask on the HxFCGI repository.
