### ISSUE TITLE
Invalid field access: index

### ISSUE THREAD

**Issue by fulopm** [HaxeFoundation/neko#152]
Hello!

I'm having some trouble with threads in Neko. After parsing a string to a type, and trying to compare one property of this type I'm getting "Invalid field access: index" exception in line 44.

See my shortened code below (especially the comments):
https://gist.github.com/fulopm/aba69515336dfa832575c1aee3b52733

Tell me if you need more details to figure out the problem, and sorry in case if it's not a bug of Neko.

**Comment by ncannasse** [comment]
Msg.Type is a string and not an enum, you cannot switch on it this way, you have to use an abstract enum for that.
