### ISSUE TITLE
Few issues while compiling neko on armhf architecture

### ISSUE THREAD

**Issue by CoruNethron** [HaxeFoundation/neko#155]
This [patch](https://github.com/HaxeFoundation/neko-debian/blob/master/debian/patches/mincoming-stack-boundary.diff) is also necessary when compiling neko under Alpine linux on armhf architecture.

And somehow it determines, wrong endiannes for my platform, so i used to fix it that way:
```
git checkout v2-1-0
sed -i -E "s/#if defined\(OS_WINDOWS\)/#if \(1\)/g" ./libs/common/osdef.h
sed -i -E "s/#ifdef NEKO_WINDOWS/#if \(1\)/g" ./vm/module.c
```

I know, that it's dirty workaround, but it helps me to successfully compile and run neko.

Maybe you consider to use simple macro, that will help to determine endianness at runtime, when compiling project.

**Comment by ppenzin** [comment]
CMake has a function to determine endianness (at least since verion 3): https://cmake.org/cmake/help/v3.0/module/TestBigEndian.html

May be this can be solved by generating a header.

**Comment by ppenzin** [comment]
Anyone minds if I look at this?

**Comment by CoruNethron** [comment]
I'll try to use TestBigEndian, next time i build neko and set approptiate variables.

**Comment by ppenzin** [comment]
I have a pending fix. @CoruNethron you can try to build it from my fork and see if it works for you.

**Comment by CoruNethron** [comment]
I confirm, that with https://github.com/ppenzin/neko/ commit `51fe00e`
I can just `cmake, make, make install` and then successfully run few helloworlds under neko
My environment is Cubieboard A10 / `armhf` + Linux kernel 4.9.5 + Alpine linux 3.5.0

**Comment by ppenzin** [comment]
I am not sure what is the usual process for closing issues, but @andyli merged the code to generate endianness into neko's master branch. @CoruNethron do you wnat to check it or should we close?

**Comment by CoruNethron** [comment]
I'll check next week, now unable, cause of missing HW.

**Comment by andyli** [comment]
It should work now, if not, open a new issue :)
