### ISSUE TITLE
neko-2.1.0 build error

### ISSUE THREAD

**Issue by MegaMcVolt** [HaxeFoundation/neko#158]
OS - Slackware 14.2 (Linux 4.4.38 (x86_64))
Desktop environment - XFCE 4

**The part where the errors occurred when compiling:**
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- set STATIC_DEPS to nothing
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found Git: /usr/bin/git (found version "2.11.0") 
-- GC: /usr/include
-- GC_LIBRARIES: /usr/lib64/libgc.so
-- GC_STATIC_LIBRARIES: GC_STATIC_LIBRARIES-NOTFOUND
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Checking for module 'zlib'
--   Found zlib, version 1.2.10
-- Found dynamic MySQL client library: /usr/lib64/mariadb/libmysqlclient.so
-- Found statc MySQL client library: /usr/lib64/mariadb/libmysqlclient.a
-- Looking for LIBMARIADB
-- Looking for LIBMARIADB - found
-- Found MariaDB Connector-C
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2k") 
-- Found PCRE 
-- Checking for module 'sqlite3'
--   Found sqlite3, version 3.16.2
-- Checking for module 'gtk+-2.0'
--   Found gtk+-2.0, version 2.24.31
-- Found APACHE: /usr/include/httpd  
-- Found APR: /usr/lib64/libapr-1.so
-- Found APRUTIL: /usr/lib64/libaprutil-1.so
-- Found MBEDTLS_LIBRARIES: /usr/lib64/libmbedtls.a;/usr/lib64/libmbedcrypto.a;/usr/lib64/libmbedx509.a
-- Found MBEDTLS_STATIC_LIBRARIES: /usr/lib64/libmbedtls.a;/usr/lib64/libmbedx509.a;/usr/lib64/libmbedcrypto.a
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/build/development/neko/neko-2.1.0/build
Scanning dependencies of target libneko
[  1%] Building C object CMakeFiles/libneko.dir/vm/alloc.c.o
/tmp/build/development/neko/neko-2.1.0/vm/alloc.c: В функции «neko_gc_init»:
/tmp/build/development/neko/neko-2.1.0/vm/alloc.c:124:2: предупреждение: «GC_all_interior_pointers» is deprecated [-Wdeprecated-declarations]
  GC_all_interior_pointers = 0;
  ^
In file included from /tmp/build/development/neko/neko-2.1.0/vm/alloc.c:45:0:
/usr/include/gc/gc.h:143:31: замечание: declared here
 GC_API GC_ATTR_DEPRECATED int GC_all_interior_pointers;
                               ^
/tmp/build/development/neko/neko-2.1.0/vm/alloc.c:132:2: предупреждение: «GC_java_finalization» is deprecated [-Wdeprecated-declarations]
  GC_java_finalization = 1;
  ^
In file included from /tmp/build/development/neko/neko-2.1.0/vm/alloc.c:45:0:
/usr/include/gc/gc.h:169:31: замечание: declared here
 GC_API GC_ATTR_DEPRECATED int GC_java_finalization;
                               ^
/tmp/build/development/neko/neko-2.1.0/vm/alloc.c:134:2: предупреждение: «GC_no_dls» is deprecated [-Wdeprecated-declarations]
  GC_no_dls = 1;
  ^
In file included from /tmp/build/development/neko/neko-2.1.0/vm/alloc.c:45:0:
/usr/include/gc/gc.h:257:31: замечание: declared here
 GC_API GC_ATTR_DEPRECATED int GC_no_dls;
                               ^
[  2%] Building C object CMakeFiles/libneko.dir/vm/builtins.c.o
[  4%] Building C object CMakeFiles/libneko.dir/vm/callback.c.o
[  5%] Building C object CMakeFiles/libneko.dir/vm/elf.c.o
[  7%] Building C object CMakeFiles/libneko.dir/vm/interp.c.o
[  8%] Building C object CMakeFiles/libneko.dir/vm/load.c.o
[ 10%] Building C object CMakeFiles/libneko.dir/vm/objtable.c.o
[ 11%] Building C object CMakeFiles/libneko.dir/vm/others.c.o
[ 13%] Building C object CMakeFiles/libneko.dir/vm/hash.c.o
[ 14%] Building C object CMakeFiles/libneko.dir/vm/module.c.o
[ 16%] Building C object CMakeFiles/libneko.dir/vm/jit_x86.c.o
[ 17%] Building C object CMakeFiles/libneko.dir/vm/threads.c.o
[ 19%] Linking C shared library bin/libneko.so
[ 19%] Built target libneko
Scanning dependencies of target zlib.ndll
[ 20%] Building C object CMakeFiles/zlib.ndll.dir/libs/zlib/zlib.c.o
[ 22%] Linking C shared module bin/zlib.ndll
[ 22%] Built target zlib.ndll
Scanning dependencies of target std.ndll
[ 23%] Building C object CMakeFiles/std.ndll.dir/libs/std/buffer.c.o
[ 25%] Building C object CMakeFiles/std.ndll.dir/libs/std/date.c.o
[ 26%] Building C object CMakeFiles/std.ndll.dir/libs/std/file.c.o
[ 28%] Building C object CMakeFiles/std.ndll.dir/libs/std/init.c.o
[ 29%] Building C object CMakeFiles/std.ndll.dir/libs/std/int32.c.o
[ 31%] Building C object CMakeFiles/std.ndll.dir/libs/std/math.c.o
[ 32%] Building C object CMakeFiles/std.ndll.dir/libs/std/string.c.o
[ 34%] Building C object CMakeFiles/std.ndll.dir/libs/std/random.c.o
[ 35%] Building C object CMakeFiles/std.ndll.dir/libs/std/serialize.c.o
[ 37%] Building C object CMakeFiles/std.ndll.dir/libs/std/socket.c.o
[ 38%] Building C object CMakeFiles/std.ndll.dir/libs/std/sys.c.o
[ 40%] Building C object CMakeFiles/std.ndll.dir/libs/std/xml.c.o
[ 41%] Building C object CMakeFiles/std.ndll.dir/libs/std/module.c.o
[ 43%] Building C object CMakeFiles/std.ndll.dir/libs/common/sha1.c.o
[ 44%] Building C object CMakeFiles/std.ndll.dir/libs/std/md5.c.o
[ 46%] Building C object CMakeFiles/std.ndll.dir/libs/std/unicode.c.o
[ 47%] Building C object CMakeFiles/std.ndll.dir/libs/std/utf8.c.o
[ 49%] Building C object CMakeFiles/std.ndll.dir/libs/std/memory.c.o
[ 50%] Building C object CMakeFiles/std.ndll.dir/libs/std/misc.c.o
[ 52%] Building C object CMakeFiles/std.ndll.dir/libs/std/thread.c.o
[ 53%] Building C object CMakeFiles/std.ndll.dir/libs/std/process.c.o
[ 55%] Building C object CMakeFiles/std.ndll.dir/libs/std/elf_update.c.o
[ 56%] Linking C shared module bin/std.ndll
[ 56%] Built target std.ndll
Scanning dependencies of target nekovm
[ 58%] Building C object CMakeFiles/nekovm.dir/vm/stats.c.o
[ 59%] Building C object CMakeFiles/nekovm.dir/vm/main.c.o
[ 61%] Linking C executable bin/neko
[ 61%] Built target nekovm
Scanning dependencies of target compilers
[ 62%] Generating bin/nekoc, bin/nekoml, bin/nekotools, bin/test.n
neko/Main
IO
String
List
Array
Core
Buffer
neko/Printer
neko/Ast
Lexer
LexEngine
Hashtbl
neko/Binast
neko/Compile
Map
neko/Bytecode
neko/Xml
Xml
neko/Console
neko/Parser
neko/Lexer
Reflect
Stack
neko/Linker
neko/Doc
Sys
Args
nekoml/Main
IO
String
List
Array
Core
Buffer
neko/Printer
neko/Ast
Lexer
LexEngine
Hashtbl
nekoml/Type
neko/Compile
Map
neko/Bytecode
Reflect
nekoml/Neko
nekoml/Typer
nekoml/Ast
nekoml/Match
Set
nekoml/Parser
nekoml/Lexer
neko/Lexer
neko/Parser
neko/Binast
neko/Xml
Xml
Sys
Zip
Stack
Args
Tools
tools/nekoboot
Sys
List
Array
Core
String
Buffer
IO
WebServer
Hashtbl
Lexer
LexEngine
Stack
Reflect
Args
Net
[ 64%] Generating bin/nekoml.std
[ 64%] Built target compilers
Scanning dependencies of target mysql5.ndll
[ 65%] Building C object CMakeFiles/mysql5.ndll.dir/libs/common/sha1.c.o
[ 67%] Building C object CMakeFiles/mysql5.ndll.dir/libs/common/socket.c.o
[ 68%] Building C object CMakeFiles/mysql5.ndll.dir/libs/mysql/my_proto/my_proto.c.o
[ 70%] Building C object CMakeFiles/mysql5.ndll.dir/libs/mysql/my_proto/my_api.c.o
[ 71%] Building C object CMakeFiles/mysql5.ndll.dir/libs/mysql/mysql.c.o
[ 73%] Linking C shared module bin/mysql5.ndll
[ 73%] Built target mysql5.ndll
Scanning dependencies of target ssl.ndll
[ 74%] Building C object CMakeFiles/ssl.ndll.dir/libs/ssl/ssl.c.o
[ 76%] Linking C shared module bin/ssl.ndll
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedtls.a(ssl_tls.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedtls.a(debug.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedtls.a(ssl_ciphersuites.c.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedtls.a(ssl_cli.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedtls.a(ssl_srv.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(bignum.c.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(cipher.c.o): relocation R_X86_64_32 against undefined symbol `mbedtls_cipher_supported' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(ctr_drbg.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(des.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(dhm.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(ecp.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(ecp_curves.c.o): relocation R_X86_64_32S against `.data' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(entropy.c.o): relocation R_X86_64_32S against symbol `mbedtls_platform_entropy_poll' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(entropy_poll.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(error.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(gcm.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(md.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(md5.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(oid.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(pem.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(pk.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(pk_wrap.c.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(pkparse.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(ripemd160.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(rsa.c.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(sha1.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(sha256.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(sha512.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(timing.c.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(aes.c.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(arc4.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(base64.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(blowfish.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(camellia.c.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(ccm.c.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(ecdsa.c.o): relocation R_X86_64_32S against symbol `mbedtls_hmac_drbg_random' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(hmac_drbg.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedcrypto.a(pkcs5.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedx509.a(x509_crt.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../lib64/libmbedx509.a(x509.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
/usr/lib64/gcc/x86_64-slackware-linux/5.4.0/../../../../x86_64-slackware-linux/bin/ld: final link failed: Раздел, непредставимый для вывода
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
make[2]: *** [CMakeFiles/ssl.ndll.dir/build.make:100: bin/ssl.ndll] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:272: CMakeFiles/ssl.ndll.dir/all] Ошибка 2
make: *** [Makefile:161: all] Ошибка 2

**Comment by andyli** [comment]
Looks like the mbedtls you installed is not compiled with `-fPIC`. You may let CMake download and compile a proper version of mbedtls by using
```bash
cmake -DSTATIC_DEPS=MbedTLS
```

**Comment by MegaMcVolt** [comment]
Thank you so much!
I recompiled mbedtls with -fPIC
After that, neko compiled successfully!
Thank you for your quick response to my problem.
Long life to you, and good health!
Sorry for my English...
