### ISSUE TITLE
limitations of fromCharCode on Neko not documented, and functionality limiting.

### ISSUE THREAD

**Issue by Justinfront** [HaxeFoundation/neko#161]
Neko seems very limited in regard to "String.fromCharCode" this is not documented in the Haxe documentation here:
http://api.haxe.org/String.html

For instance with Javascript a fromCharCode experiment prints out a wide range or characters, need to explore correct values for some of the enum but the point still holds, it fails more than succeeds on Neko.
// JS 
http://try-haxe.mrcdk.com/#9F342

11:29:08:262   A,a,À,à,Á,á,Â,â,Ã,ã,Ä,ä,Å,å,Æ,æ,ª,B,b,C,c,Ç,ç,D,d,E,e,È,è,É,é,Ê,ó,Ë,ë,F,f,,G,g,H,h,I,i,Ì,î,Í,í,Î,î,Ï,ï,J,j,K,k,L,l,M,m,N,n,Ñ,ñ,O,o,Ò,ò,Ó,ó,Ô,ô,Õ,ó,Ö,ö,Ø,Ă,P,p,Q,q,R,r,S,s,,,ß,T,t,U,u,Ù,ù,Ú,ú,Û,û,Ü,ü,V,v,W,w,X,x,Y,y,,ÿ,Ý,ý,Z,z,,,0,1,2,3,4,5,6,7,8,9,¼,½,¾,¹,²,³,°, ,!,¡,#,&,*,,,-,.,~,/,\,:,;,?,¿,@,(,),[,],{,},|,¦,,,,_,,,©,®,$,,¢,£,¤,¥,',",,,,,`,´,,^,,,,,«,»,<,>,%,=,+,×,÷,±,,,,,,,Œ,œ,§,¨,¬,­,µ,¶,·,¸,º,Ð,Þ,ð,þ,А,Б,В,Г,Д,Е,Ж,З,И,Й,К,Л,М,Н,О,П,Р,С,Т,У,Ф,Х,Ц,Ч,Ш,Щ,Ъ,Ы,Ь,Э,Ю,Я,а,б,в,г,д,е,ж,з,и,й,к,л,м,н,о,п,р,с,т,у,ф,х,ц,ч,ш,щ,ъ,ы,ь,э,ю,я,Α,α,Β,β,Γ,γ,Δ,δ,Ε,ε,Ζ,ζ,Η,Γ,Θ,θ,Ι,ι,Κ,κ,Λ,λ,Μ,μ,Ν,͙,Ξ,ξ,Ο,ο,Π,π,Ρ,ρ,Σ,σ,ς,Τ,τ,Υ,υ,Φ,φ,Χ,χ,Ψ,ψ,Ω,ω,ð,÷,ò,ó,û,ã,ü,ì,µ,ä,ï,☺

But for Neko it seems quite broken, I understand that the internal implemention may need changing but String.fromCharCode does not work as expected and is not documented to fail, please let me know if this issue should be raised instead on haxe repository.

// Neko
http://try-haxe.mrcdk.com/#1bFc9
http://try-haxe.mrcdk.com/program/1bFc9/run?r=0.09250396470977684

Test.hx:349: [A,a,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,B,b,C,c,�,�,D,d,E,e,�,�,�,�,�,�,�,�,F,f,�,G,g,H,h,I,i,�,�,�,�,�,�,�,�,J,j,K,k,L,l,M,m,N,n,�,�,O,o,�,�,�,�,�,�,�,�,�,�,�,,P,p,Q,q,R,r,S,s,�,�,�,T,t,U,u,�,�,�,�,�,�,�,�,V,v,W,w,X,x,Y,y,�,�,�,�,Z,z,�,�,0,1,2,3,4,5,6,7,8,9,�,�,�,�,�,�,�, ,!,�,#,&,*,,,-,.,~,/,\,:,;,?,�,@,(,),[,],{,},|,�,�,�,�,_,,�,�,�,$,�,�,�,�,�,',",�,�,�,�,`,�,�,^,�,�,�,�,�,�,<,>,%,=,+,�,�,�,�,�,�,�,�,�,R,S,�,�,�,�,�,�,�,�,�,�,�,�,�,,,,,,,,,,,,,,,,, ,!,",#,$,%,&,',(,),*,+,,,-,.,/,0,1,2,3,4,5,6,7,8,9,:,;,<,=,>,?,@,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,Y,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,�,:]

**Comment by ncannasse** [comment]
Neko does not support properly Unicode atm, we are working on it for Haxe 4.
