### ISSUE TITLE
Matchsub not matching ^ at start of string

### ISSUE THREAD

**Issue by rhacking** [HaxeFoundation/neko#164]
Environment:
macOS 10.12.3 (16D32)
Haxe 3.4.0
Neko 2.1.0

```Haxe
~/^/.matchSub("1 ", 1)
```
The above code returns true when using the the JS target, but returns false on the Neko target. Looking at the documentation [here](http://api.haxe.org/EReg.html), there is no mention of differences on the Neko target regarding the function of ^ for matchSub. If you manually take the substring, like this
```Haxe
~/^/.match("1 ".substr(1))
```
the result is equal on JS and Neko (true).

**Comment by tobil4sk** [comment]
Closing in favour of https://github.com/HaxeFoundation/haxe/issues/10606
