### ISSUE TITLE
test.n missing from binaries

### ISSUE THREAD

**Issue by Kinrany** [HaxeFoundation/neko#168]
I'm trying to install Neko on Windows 7. I'm following the [Starter's Guide](http://nekovm.org/doc/begin), and it contains a list of files that should be present in the archive, which includes `test.n`. This file is also used later to make sure that the `neko` console command works as expected.

Neither is `test.n` present in any other binaries as far as I can tell.

**Comment by ibilon** [comment]
@andyli were you the one who uploaded the 2.1 binaries? (https://github.com/HaxeFoundation/nekovm.org/commit/0bd78a0fdd03b97b10c04641e6d02dda2b2c130c)

I have the file in my build folder, so I guess this is a packaging issue.

**Comment by andyli** [comment]
Yes, I did the upload. The test.n is built and available in the bin folder, but it is not installed (by `make install`) so it is missing from the archive, which is produced by `make package`. I thought that test.n is only for testing, so I intentionally excluded that when I introduce the CMake build files, but I guess I should have kept it.

Updating existing release archives is not really a good practice, so I will update the starter's guide to remove test.n instead.
