### ISSUE TITLE
DateTools.format("%T") crashes on Windows

### ISSUE THREAD

**Issue by ashes999** [HaxeFoundation/neko#169]
Hi,

I've seen this issue across three Windows machines (Windows 8 and Windows 10), consistently; always with the latest Neko (2.1.0).

This simple line crashes the `neko.exe` process:

`DateTools.format(Date.now(), "%T");`

Note that `using DateTools` and running `Date.now().Format("%T")` yields the same result. Also note that I usually do something interesting with the value (trace it, assign it to a variable) but that's not necessary to reproduce the crash.

It also doesn't seem to be specific to `Date.now`; I can see the same crash when I create a date object using the constructor, eg. `DateTools.format(new Date(2016, 12, 31, 17, 45, 59), "%T")`.

If it helps, Windows Event Viewer reports these details, under the Application event-viewer log with event ID 1000 and task category 100:

```
Faulting application name: neko.exe, version: 0.0.0.0, time stamp: 0x572e1296
Faulting module name: MSVCR120.dll, version: 12.0.21005.1, time stamp: 0x524f7ce6
Exception code: 0xc0000409
Fault offset: 0x000a46a9
Faulting process id: 0x4244
Faulting application start time: 0x01d3040739c05cc1
Faulting application path: C:\HaxeToolkit\neko\neko.exe
Faulting module path: C:\HaxeToolkit\neko\MSVCR120.dll
Report Id: f113c0fc-aad7-4d44-8cf0-46b622616c0a
Faulting package full name: 
Faulting package-relative application ID: 
```

My app runs fine with Neko on Linux.

**Comment by jonasmalacofilho** [comment]
Neko delegates formatting dates to the system's `strftime` implementation.

Apparently `%T` [isn't supported](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l) by Windows' `strftime`.

**Comment by ashes999** [comment]
I guess that means there's nothing to "fix" in Haxe or Neko; although I think it's worth:

- Adding this information to the `DateUtils` docs in Haxe so people understand what are and aren't valid values
- Crashing with an exception that clearly indicates what the problem is

I'll try to get the same value using a combination of other values that are available.
