### ISSUE TITLE
Releasing Neko 2.2.0

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/neko#174]
We have again accumulated [quite a few fixes](https://github.com/HaxeFoundation/neko/blob/master/CHANGES), mostly on CMake/packaging. Let's release a version?

@ncannasse If you agree, and don't have anything to adjust, I will take care of releasing it.

**Comment by ncannasse** [comment]
Please do, I have little Neko time, focusing on HL now ;)

**Comment by andyli** [comment]
Sill in progress of updating neko packages here and there, but I will just close this for now.
