### ISSUE TITLE
apt-get for Ubuntu 18.04.1

### ISSUE THREAD

**Issue by yar3333** [HaxeFoundation/neko#192]
I try to install neko on Ubuntu 18.04.1:
```
apt-get install neko

The following packages have unmet dependencies:
 neko : Depends: libmariadb2 (>= 2.0.0) but it is not installable
        Depends: libmbedcrypto0 (>= 2.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Now I install package manually. :)

**Comment by andyli** [comment]
I've just tested with the ubuntu:18.04 docker image, neither the neko from ubuntu's repo or from ppa:haxe/releases reproduces the issue. Did you installed something that conflict with libmariadb2 or libmbedcrypto0? Try apt-get install the two first and there should be some more hints.

**Comment by yar3333** [comment]
May be the problem is a tiny edition of Ubuntu... I test this on VDS... I think, issue may be closed.
