### ISSUE TITLE
Make a release for Haxe 4

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/neko#198]
An issue to not forget we need a new neko release for Haxe 4

**Comment by emugel** [comment]
Still no neko 2.3 for haxe 4.0? :(
I guess for next minor release

**Comment by RealyUniqueName** [comment]
Neko 2.3 is already released and can be installed from https://nekovm.org/download/
I thought our CI automatically packages latest neko release with Haxe installers, but apparently that was an oversight of mine.
Haxe installers will get updated Neko with the release of Haxe 4.0.1

**Comment by AlexHaxe** [comment]
Copyright year needs an update: https://github.com/HaxeFoundation/neko/blob/ee437af03bf5c2caa5a2fb7cb909e73ccf1315c9/src/nekoml/Main.nml#L80

Also neko-2.3.0-raspbian.tar.gz from https://github.com/HaxeFoundation/neko/releases/tag/v2-3-0 contains version 2.0.0 from 2014.

**Comment by RealyUniqueName** [comment]
Somehow I didn't see raspbian not updated since 2014.
Removed it from release assets.
