### ISSUE TITLE
Define module at runtime

### ISSUE THREAD

**Issue by 0xF6** [HaxeFoundation/neko#212]
Is possible to define a module at runtime?

**Comment by RealyUniqueName** [comment]
It's possible to load pre-compiled modules at runtime: https://api.haxe.org/neko/vm/Loader.html

**Comment by 0xF6** [comment]
Yes.
And without a pre-compiled module possible?

**Comment by ALANVF** [comment]
You could always write Neko code to a temporary file

**Comment by 0xF6** [comment]
I needed modules to declare global external functions from the system that the VM is embedded in, and I found another solution:


I modified `alloc.c` by adding `get_neko_builtins` method
```C
// vm/alloc.c
EXTERN value* get_neko_builtins() {
	return neko_builtins;
}
```
For declaration of global functions
```C#
public unsafe delegate void neko_delegate1(void* a1);
// ...
void func1(void* a1)
{
    // ...
}
void** g= get_neko_builtins();
nint p = Marshal.GetFunctionPointerForDelegate((neko_delegate)func1);
void* f = neko_alloc_function((void*) p, 1, "$dotnetfunc1");
neko_alloc_field(g[0], neko_val_id("dotnetfunc1"), f);
```
and neko code with calling global function:
```haxe
$exports.calling_test = function(){
    return $dotnetfunc1("test-string");
}
```
