### ISSUE TITLE
Any good starting points for integrating a language to the nekovm?

### ISSUE THREAD

**Issue by timo-cmd2** [HaxeFoundation/neko#227]
Hello all 👋🏻 

Just stumbled upon NekoVM. Great job, keep it up! 

I have just recently started to implement a programming language on top of RubiniusVM, but that seems to be stalled. Now my choices wide, with NekoVM in mind. Are there any good docs for integrating a language on NekoVM?

Thanks for the support

Best regards

Timo

**Comment by RealyUniqueName** [comment]
I'm afraid NekoVM is not actively maintained anymore.

**Comment by timo-cmd2** [comment]
Oh my gosh nooo
