### ISSUE TITLE
Shell completion 

### ISSUE THREAD

**Issue by tong** [HaxeFoundation/neko#24]
How about adding shell completion scripts?
https://gist.github.com/tong/6893397

**Comment by ncannasse** [comment]
Maybe @andyli want to have this in neko package ?

**Comment by andyli** [comment]
Ya, sounds good. @tong would you mind to specify a license for the script? Public domain would be great, or else any free license is ok too.

**Comment by tong** [comment]
done.

**Comment by andyli** [comment]
@tong Thanks! I've added it in https://github.com/HaxeFoundation/neko-debian/commit/ea4c44e1f54dc39b70db5418350673f2cbd9619a. Waiting for a Debian guy to check and upload.

**Comment by tong** [comment]
@andyli High5 for the debian package! (finally)

**Comment by tong** [comment]
Imho this should be part of the neko project, not just neko-debian.
