### ISSUE TITLE
libmbedtls 3 not supported

### ISSUE THREAD

**Issue by concatime** [HaxeFoundation/neko#252]
Hi,
I know this package is not supported, but I just want to say that it does not compile with libmbedtls v3,

**Comment by dnewhall** [comment]
In case someone else tries to fix this, this is what needs to be done, as far as I can tell:
(See https://github.com/Mbed-TLS/mbedtls/blob/development/docs/3.0-migration-guide.md)
In lib/ssl/ssl.c:
- Remove #include <mbedtls/net.h>
- The field ext_types in struct mbedtls_x509_crt is now private. There should be some function/macro now to test it.
- mbedtls_pk_parse_key takes an extra argument for a random state.
- mbedtls_pk_sign takes a size for the buffer.
