### ISSUE TITLE
Crash on Mac - std@date_utc_format

### ISSUE THREAD

**Issue by darmie** [HaxeFoundation/neko#253]
*DEPRECATION NOTICE: Neko is not actively maintained anymore. You can open an issue anyway, but don't expect to get response from developers.*

```
npx haxelib run dox -i bin -o docs/pages
Called from C:\Users\fischej\AppData\Roaming/haxe/versions/4.2.3/std/neko/_std/Date.hx line 126
Uncaught exception - load.c(357) : Primitive not found : std@date_utc_format(2)
```

**Comment by tobil4sk** [comment]
Your Haxe and Neko versions may be incompatible. You should be able to check the neko version (assuming you are using lix) through `npx neko`. If it is below 2.3.0, then you should update because that may be the reason why the function is missing.

**Comment by darmie** [comment]
How do I update Neko?

**Comment by tobil4sk** [comment]
I'm not familiar with how lix handles neko versions, but you could try rerunning the [Mac installer for haxe](https://haxe.org/download/) if that's how you originally installed haxe, and it should give you the newest version of neko. If you've only ever installed haxe and neko using lix then it's probably best to ask in the [lix repository](https://github.com/lix-pm/lix.client) how to update it.

**Comment by tobil4sk** [comment]
@darmie Did you manage to solve this issue?

**Comment by tobil4sk** [comment]
Going to assume that updating neko fixed the issue, if not feel free to reopen.
