### ISSUE TITLE
Any syntax of the Neko ML language ?

### ISSUE THREAD

**Issue by longde123** [HaxeFoundation/neko#261]
*DEPRECATION NOTICE: Neko is not actively maintained anymore. You can open an issue anyway, but don't expect to get response from developers.*
eg The syntax of the Neko language https://nekovm.org/specs/syntax/

Neko ML language ?

**Comment by tobil4sk** [comment]
There is a short guide here: https://nekovm.org/doc/nekoml/

As it says, the best way after reading that is probably to read the nekoml standard library and the compiler sources to figure out.
