### ISSUE TITLE
Makefile portable_install target, header files uninstall

### ISSUE THREAD

**Issue by MetaChrome** [HaxeFoundation/neko#30]
The following is an append at line 131 in Makefile. It would be useful to have this in the repo (as well as the archiving that generates a distribution archive) so it doesn't have to be merged on every change.

        rm -rf ${INSTALL_PREFIX}/include/neko*.h

	portable_install:
		mkdir -p ${INSTALL_PREFIX} ${INSTALL_PREFIX}/include
		cp bin/neko bin/nekoc bin/nekotools bin/nekoml bin/nekoml.std bin/${LIBNEKO_NAME} bin/*.ndll ${INSTALL_PREFIX}
		cp vm/neko*.h ${INSTALL_PREFIX}/include

	portable_uninstall_incl_dir:
		rm -rf ${INSTALL_PREFIX}

	portable_uninstall:
		rm -rf ${INSTALL_PREFIX}/neko* ${INSTALL_PREFIX}/${LIBNEKO_NAME} ${INSTALL_PREFIX}/*.ndll ${INSTALL_PREFIX}/include/neko*.h

**Comment by ncannasse** [comment]
Haxe Foundation is working on integrating haxe and neko in package managers, @andyli might want to have a look at it.
