### ISSUE TITLE
Download tarball is broken by PHP warnings

### ISSUE THREAD

**Issue by tkawachi** [HaxeFoundation/neko#49]
http://nekovm.org/_media/neko-2.0.0-linux64.tar.gz shows following:

![screen shot 2015-01-15 at 16 37 40](https://cloud.githubusercontent.com/assets/22657/5753956/ed37f506-9cd4-11e4-87ff-06eb6846d264.png)

It seems that PHP warnings are inserted before the contents.

**Comment by ncannasse** [comment]
@pperidont @delahee help please :)

**Comment by tkawachi** [comment]
Is there any download site available?

How about uploading release builds on GitHub? We don't have to care about web server status because GitHub guys care about it.
ref. https://help.github.com/articles/creating-releases/

**Comment by Simn** [comment]
This has been resolved.
