### ISSUE TITLE
http://nekovm.org/ is down

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/neko#50]
Not sure where to report this.

**Comment by delahee** [comment]
This site is hosted at MT but we're out of office, we ll check this out
Monday.

**Comment by delahee** [comment]
Update : We are sending the data to the haxefoundation that will setup back the site, The nekovm service should resume today.

**Comment by stahlratte** [comment]
sooo... any news? i'd like to install haxe on linux and the install script is not working. are there any mirrors for the binaries?

**Comment by skial** [comment]
builds.haxe.org has neko
<http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/neko/>
supposedly for each platform, but I've never tried them before.

**Comment by stahlratte** [comment]
thx. those didn't work out with the haxe/openfl install script, but i just used neko from apt-get and deleted the neko stuff from the script for the time beeing.

**Comment by 96AA48** [comment]
It's wednesday now, still no site up. I need this for the Haxe install script as well.

**Comment by delahee** [comment]
For those who need backup, there are mirrors and google cache, you can also build it from source pretty easily :)

The resurection might take a few days as our network admin  is ill these days :) and transfer to hf can take a few days too (proper dns propagation and installs)

**Comment by tkawachi** [comment]
The install script should be modified to try multiple mirrors for such a situation.

**Comment by ncannasse** [comment]
Should be up and running again, this time hosted by HaxeFoundation, thanks to MotionTwin
