### ISSUE TITLE
OpenFL + Nape, codesize too big?

### ISSUE THREAD

**Issue by starburst997** [HaxeFoundation/neko#51]
Since this seems like a Neko issue I thought I would fill an issue properly.
See https://github.com/openfl/openfl/issues/158 and https://github.com/deltaluca/nape/issues/77

```haxe
class Main extends openfl.display.Sprite {

 public function new () { 
 super();

 var tf = new openfl.text.TextField();
 tf.text = "Hi There";
 addChild(tf);


 var space = new nape.space.Space();
 }

}
```

With the 2.0.0 code this crash with a 
```
Uncaught exception - std@module_read
```

Building the latest Neko from source fix this, however in my game it still output the same error, probably from the added codesize of my game?

Also on a probably related note, on another project I get invalid call on functions, putting them as inline will fix it but then it is another function that will have invalid call, and this seems to go in a logical order, is there a limit on the number of functions a program can have? Where could I bump this number.

**Comment by ncannasse** [comment]
Could you try to debug in  vm/module.c which cause is triggering the std@module_read error ?

**Comment by lewislepton** [comment]
ive been getting this recently as well using NAPE, which i would like to use. how can i work around it? 
or where should i go to at least hopefully address this?
what steps to take?

thanks

**Comment by lewislepton** [comment]
actually someone has just helped with the outcome to bypass and allow it to run
in the project.xml, put in these 2 lines inside project.xml

```
<haxedef name="no-inline" />
<haxedef name="dce=full" />
```

hopefully something more full time can be implemented for future folk, but still its a nice work-around ;)

**Comment by thomasuster** [comment]
I'm also hitting this for Pakka Pets, even with 
```
<haxedef name="no-inline" />
<haxedef name="dce=full" />
```

**Comment by ncannasse** [comment]
@thomasuster could you get some informations in vm/module.c to know where it stops ? Or if you can send me the broken `.n` privately.

**Comment by thomasuster** [comment]
@ncannasse Wasn't able to get neko building on OSX. Is there a doc somewhere for this or should I not bother? My email is thomas@proto-games.com. Where should I send the .n to?

**Comment by ncannasse** [comment]
send the .n to nicolas at haxe.org, I will look into it

**Comment by ncannasse** [comment]
It was confirmed that it was a max code size limitation that was already increased in GIT version.
