### ISSUE TITLE
Sqlite3 static lib

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/neko#52]
I just noticed that in df3f12c09d19ea098fce3ecc1ab1f610cc9ca9d5 @nadako  didn't made a static library for sqlite3.lib, so it now complains about missing sqlite3.dll. For NekoVM I prefer that all 3rd party libraries are statically linked. We have to fix this before release.

@nadako could you take care of it ?

**Comment by ncannasse** [comment]
PS : this requires also to be compiled with /MT (multithreaded static standard library)

**Comment by ncannasse** [comment]
@nadako up (or I would have to revert to previous sqlite version before releasing ;-) )

**Comment by nadako** [comment]
oh, sorry i missed this issue somehow

**Comment by nadako** [comment]
btw, what version of vs should this be compiled with?

**Comment by nadako** [comment]
see #58. 
also doesn't mysqlclient have the same issue?

**Comment by ncannasse** [comment]
mysqlclient seems fine.
