### ISSUE TITLE
http://nekovm.org/ is down

### ISSUE THREAD

**Issue by dvallejof** [HaxeFoundation/neko#53]
Hi there,

it seems nekovm.org is down. I tried to install OpenFL from scratch using the Linux installer since I will be teaching a course on videogame development on Friday and didn't work. I have a previous version in my computer, but I'm afraid my students don't.

Thanks a lot for your time,  - David.

**Comment by Simn** [comment]
The site is working for me.

**Comment by dvallejof** [comment]
Sorry, it seems to be a DNS-related issue.

**Comment by Simn** [comment]
Can you resolve it? We could temporarily host neko on haxe.org if you are nervous about your course.

**Comment by dvallejof** [comment]
It's kinda odd since from the Uni network I get a DNS error with code  DNS_PROBE_FINISHED_NXDOMAIN but from a external site everything is fine.

Thanks a lot for your concern but let me first check if I can solve the issue contacting with the sysadmin.

**Comment by ncannasse** [comment]
@Simn neko website is now hosted on haxe.org
