### ISSUE TITLE
Issues with UInt and null value on neko 2.0.0 "Uncaught exception - Invalid operation (+)"

### ISSUE THREAD

**Issue by sebpatu** [HaxeFoundation/neko#54]
On neko 2.0.0 and using haxe 3.1.3
not same issue on other targets like flash or js

i get "Uncaught exception - Invalid operation (+)" for this code:
http://try.haxe.org/#b71bD
same result with UInt instead of Null<UInt>
but i have no issue if its a Int, Null<Int> or if a default value of the variable is set to something not null. If set to null, it gets same error.

**Comment by ncannasse** [comment]
I have reported the issue to Haxe repo since it should be handled at Haxe level.
