### ISSUE TITLE
On windows, neko fails to create processes from `*.cmd` or `*.bat` when given only the name

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/neko#63]
It seems to be a limitation in `CreateProcess` (used by `sys.io.Process.new`), that doesn't exist in `system` (used by `Sys.command`). That's as far as my non-existent C skill got me.

**Comment by ncannasse** [comment]
That seems fair to me. Sys.command goes through shell whereas CreateProcess requires a process path. I'm actually surprised that we can run .bat/.cmd with CreateProcess.
