### ISSUE TITLE
Nightly build needed

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/neko#64]
I would like to have the fix from https://github.com/HaxeFoundation/neko/pull/21 which seems not being included in the 2.0.0 release. Where can I find the nightly build?

**Comment by andyli** [comment]
If you're on Windows, try the one at https://ci.appveyor.com/project/HaxeFoundation/neko/build/2/artifacts
Note that you may need to install "Microsoft Visual C++ 2010 Redistributable Package" (x86), in case it complains MSVCR100.dll is missing.

If you're on Mac, `brew install neko --HEAD`.
If you're on Linux, just build it from source :)

**Comment by kevinresol** [comment]
Thanks, the windows build is what i needed :+1:
