### ISSUE TITLE
Unable to load the mod_neko2 module on apache 2.4 (windows)

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/neko#66]
Windows 7
Apache 2.4.10 (with mpm_winnt.c)
Neko latest build from AppVeyor

When tried to start apache using the `httpd` command:
```
httpd: Syntax error on line 180 of D:/xampp/apache/conf/httpd.conf: Cannot load
D:/HaxeToolkit/neko/mod_neko2.ndll into server: The specified procedure could not be found.
```

**Comment by ncannasse** [comment]
Could you try with apache 2.2 ?

**Comment by kevinresol** [comment]
with Apache 2.2 it works....

**Comment by ncannasse** [comment]
Sadly this mean we will have to rebuild a mod_neko24 with Apache 2.4 headers if we want to have compatibility for both...

**Comment by greg-dove** [comment]
Just a quick check on this issue: are there any plans to address it in the neko distribution?

**Comment by ncannasse** [comment]
@andyli what's the status of mod_neko apache versions support within neko distribution?

**Comment by andyli** [comment]
See #106

FYI, the debian and homebrew packages already provide mod_neko/tora compiled for the system apache (2.4).

**Comment by ncannasse** [comment]
New releases will provide 2.4 support
