### ISSUE TITLE
Neko jit on Debian jessie

### ISSUE THREAD

**Issue by ConstNW** [HaxeFoundation/neko#71]
I have got JIT-related errors on new debian release (x86).

```
Called from Array::__get line 291
Uncaught exception - Invalid array access
```

On turning off jit (-interp) everything works fine.

After some research found that `Array::__get` called with a wrong scope.

**Comment by ConstNW** [comment]
on nigthly builds get same error.

**Comment by sharow** [comment]
I'm sure this is #39, and this fixed ccc78c2.
I think your nightly neko is linking to old libneko.so (located /usr/lib/ or /usr/local/lib).
Can you confirm it?
```
$ ldd `which neko`
$ ldd ./neko
```
and I recommend to try git:HEAD version.

(also I don't know where is nightly builds. does it exists?)

**Comment by ConstNW** [comment]
@sharow yes, it's the same issue - libneko.so linking problem.
thanks!

neko nightly builds are at http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/neko/

**Comment by sharow** [comment]
ohh yes that is nightly build. I didn't know that. thanks! :beers:
