### ISSUE TITLE
parameter incorrectly initialized to 0

### ISSUE THREAD

**Issue by increpare** [HaxeFoundation/neko#72]
this prints 20,20 on OSX, and Flash builds, but 20,0 when run with neko. halp.

	package;

	import openfl.display.Sprite;

	class Main extends Sprite {
		
		var px:Int = Math.floor(20);
		
		public function new () {		
			super ();
			trace(Math.floor(20));
			trace(px);			
			
		}
		
	}

appeared on haxe compiler 3.1.3, OSX 10.10.3

edit: oops, forgot to link to repro project

http://ded.increpare.com/~locus/nekobug.zip

**Comment by ncannasse** [comment]
It should be reported to haxe, I've opened an issue here https://github.com/HaxeFoundation/haxe/issues/4254
