### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/neko#74]
I was at the Ufront gitter chat room today talking about how one should debug an Ufront app and the fact that there's still not interactive debugger available for it (we talked briefly about the possibility of using the experimental Nodejs backend to debug the server using https://github.com/node-inspector/node-inspector ). Since Neko is the default target afaik but there's isn't yet a native Neko interactive debugger, that made me think about Neko's future and roadmap.

I totally forgot to ask @ncannasse or @Simn about that at the conference, but it'd be nice to know what are the foundation plans for Neko, since, from my point of view, it's still a crucial component in the Haxe eco-system and it should get the attention it deserves.

**Comment by delahee** [comment]
+1
Maybe we can ask @hughsando if he could adapt the hxcpp debugger for Neko ?

**Comment by ConstNW** [comment]
:+1:

**Comment by jasononeil** [comment]
+1 for a roadmap... I'm quite happy with the technology in general, but it seems to be fairly stagnant now since Neko 2.0 was released.  If there is plans to develop it further (eg, add a debugger) it would be great to know.  If there are no plans and it is only going to receive bug fixes... then that would also be good to know.

**Comment by kevinresol** [comment]
+1 for roadmap and debugger

**Comment by ncannasse** [comment]
Neko is quite stable for now, the new release will include SSL support but apart from that I don't have time to work on debugger or other big features, so I prefer not to have a fixed roadmap for it. OTOH I'm working on something new, which could be the successor to Neko when completed.
