### ISSUE TITLE
neko display problem..

### ISSUE THREAD

**Issue by ChangJoo-Park** [HaxeFoundation/neko#76]
I use Haxeflixel on OS X yosemite and all latest version

before I update haxe and something(I don't know what to update)

then screen size is wierd

I write this issue on stackoverflow but same issue happened

http://stackoverflow.com/questions/30727749/haxeflixel-with-neko-build-screen-size-does-not-fit/30729229?noredirect=1#comment49515685_30729229

How I do this situation?

**Comment by ChangJoo-Park** [comment]
Additionaly this is only building Neko.

**Comment by andyli** [comment]
It is likely to be a HaxeFlixel/OpenFL issue, and I found that you've already reported to HaxeFlixel (https://github.com/HaxeFlixel/flixel/issues/1521).
Please report it only to the most relevant project and discuss there.
