### ISSUE TITLE
Bytes setInt32 crash

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/neko#78]
The follow code crashes with error `$sset`
```haxe
package;

import haxe.io.Bytes;

class Main 
{
	static function main() 
	{
		var b = Bytes.alloc(128 * 145 * 4);
		b.fill(0, 128 * 145 * 4, 0);
		b.setInt32(73660, 0x70ffffff);
	}
}
```

**Comment by ncannasse** [comment]
This can be reproduced with the following, because it seems `$sset` does not accept int32.
```
import haxe.io.Bytes;

class Main 
{
    static function main() 
    {
        var b = Bytes.alloc(1);
        b.set(0, 0x70ffffff);
    }
}
```

**Comment by kevinresol** [comment]
Thanks for the quick fix. btw is `Bytes` not being unit tested?

**Comment by ncannasse** [comment]
It is, but looks like not for big int32 values (please note that the runtime difference between int and int32 is a neko-specific thing)
