### ISSUE TITLE
FreeBSD support?

### ISSUE THREAD

**Issue by ppenzin** [HaxeFoundation/neko#80]
This question might have been asked before. At first glance (though I might be wrong, of course) there is nothing that should prevent porting to FreeBSD. Are there any plans to support this? Any tips in case I try to port it myself?

**Comment by ncannasse** [comment]
Neko should work perfectly on FreeBSD, since it's mostly ANSI C. Try to compile, there should be not much issues.

**Comment by ppenzin** [comment]
I [forked](https://github.com/ppenzin/neko) the repository and made [some changes](https://github.com/ppenzin/neko/commit/445f0537b637ea030864d84ccc84cf2c9f1a07d0) to get it to build. I am able to run neko, but not able to run nekoc directly, this is what I need to do to compile:
```
NEKOPATH=boot:bin bin/neko nekoc hello.neko
```
Does this look familiar?

**Comment by ppenzin** [comment]
Sorry for a confusing explanation, hopefully this is better:
```
$ bin/nekoc hello.neko
Uncaught exception - load.c(181) : Module not found : hello.neko
$ NEKOPATH=boot:bin bin/neko nekoc hello.neko
$ bin/nekoc hello
Hello world!
```
As far as I understand my `succesful' compilation uses boot/nekoc.n to compile the source file

**Comment by ibilon** [comment]
If you do `bin/nekoc` it wouldn't print
```
NekoVM 2.0.0 (c)2005-2013 Haxe Foundation
  Usage : neko <file>
```
by any chance? 

If so the most probable explanation is that the executable was stripped (`strip nekoc`) of the nekoc bytecode.

**Comment by ppenzin** [comment]
It does print that. I don't see `strip nekoc' in the build output though.

**Comment by ibilon** [comment]
If you do
```
ls -l bin/nekoc
strip bin/nekoc
ls -l bin/nekoc
```
does the file size go down?

If so then the bytecode was there but wasn't found or something.
If not then somehow the file was already stripped or the bytecode was never added.

**Comment by ppenzin** [comment]
File size does go down, so it must be not seeing the appended bytecode. 

Any other pointers would be greatly appreciated, meanwhile I will see how I can debug this.

**Comment by mwgamera** [comment]
Do you have `/proc/self/exe` or `$_` in environment? See [main.c:53](https://github.com/HaxeFoundation/neko/blob/035179c1b7e61fa140e1e68ba1c81ab85d092f7f/vm/main.c#L53).

**Comment by ppenzin** [comment]
Thanks, that is the culprit, that's not available on FreeBSD. [Fixed](https://github.com/ppenzin/neko/commit/50ac72fb5755721efc9a5079a27b5c2232a0d323), my fork builds, runs and installs.

**Comment by ppenzin** [comment]
I ran `make test`, it passed. Are there any other test suites that I can run?

**Comment by ncannasse** [comment]
Should be ok, could you open a PR with your changes ?

**Comment by ppenzin** [comment]
Would you also want to add neko to Ports Collection (and potentially binary packages)?

**Comment by ncannasse** [comment]
Sure, although I wouldn't know where to start (not familiar with BSD)

**Comment by ppenzin** [comment]
I can definitely help with that. We would need an email address and a
github commit/branch to point to. Should we start a new issue to discuss
the details?
