### ISSUE TITLE
[Feature Request] More control over Handling termination signal

### ISSUE THREAD

**Issue by Khaledgarbaya** [HaxeFoundation/neko#81]
Hi,
[Feature Request]
As far as I know It is not possible to catch the command line termination signal in Neko VM to do some further clean up.
It would be nice  if the Neko VM when handling it, call the currently running user Neko binary.
It is really import for us in our build build tool https://github.com/gameduell/duell , because duell libraries can have plugins that launches separate processes so we need a Watcher for the termination signal to notify all plugins to perform some clean up. And the tool is fully written in Haxe.

Best,
Khaled

**Comment by ncannasse** [comment]
I'm not sure I understand correctly. If you start a process with for example  sys.io.Process, the calling .exitCode() will wait until process termination and returns its exit code. If you need to run several of them and don't want to lock your application, you can use a thread that will wait for the process termination then send a message to your main thread. Does that help ?

**Comment by Khaledgarbaya** [comment]
Still we can't catch the ctrl-c for example, when the user press ctrl-c it kills all and we are not able to catch it

**Comment by ibilon** [comment]
I think he talks about the signal that the main thread receive from the os,
so that he can "propagate" it to the sub processes, allowing them to clean up before allowing the complete termination of the program.

**Comment by ncannasse** [comment]
I'm not sure Ctrl+C is catchable on all systems. On Linux I think it triggers a "Broken pipe" String exception, see  https://github.com/HaxeFoundation/neko/blob/master/vm/main.c#L195 . I guess you would like the same for OSX/Windows ?

**Comment by ncannasse** [comment]
Actually it should work for OSX as well

**Comment by ncannasse** [comment]
Windows have SetConsoleCtrlHandler for it, we could easily use it there as well https://msdn.microsoft.com/en-us/library/windows/desktop/ms685049(v=vs.85).aspx

**Comment by waneck** [comment]
Afaik, CTRL C raises a SIGTERM on linux. Doesn't it?

**Comment by Khaledgarbaya** [comment]
@ibilon yes exactly that 
@ncannasse that would be great !
something like so
```#include <stdio.h>
#include <signal.h>
 
/* Signal Handler for SIGINT */
void sigintHandler(int sig_num)
{
    switch (sig_num) {
                //...
                case 2:
                    println("ctrl-c is pressed.");
                    Sys.exit(0);
                 break;
              //....
            }
}
 
int main ()
{
    /* Set the SIGINT (Ctrl-C) signal handler to sigintHandler 
       Refer http://en.cppreference.com/w/c/program/signal */
    signal(SIGINT, sigintHandler);
 
    /* Infinite loop */
    while(1)
    {        
    }
    return 0;
}```

**Comment by ncannasse** [comment]
Right, it's actually SIGINT. Now I'm not sure we want to have this by default since for instance this would make the following code not being able to exit with Ctrl+C

```
while( true ) {
    try {
        while(true) {}
    } catch( e : Dynamic ) {
    }
}
```

I'll look at adding a primitive that allows Ctrl+C exceptions to be caught.

**Comment by Khaledgarbaya** [comment]
I am closing this issue since there was no more comments for a long time
