### ISSUE TITLE
Where SHCreateItemFromParsingName is used?

### ISSUE THREAD

**Issue by vyal** [HaxeFoundation/neko#89]
I am trying to run openfl in Windows XP. But neko claims shell32 don't have 'SHCreateItemFromParsingName'. Trying to fix the issue for my personal build, but I am unable to find where exactly 'SHCreateItemFromParsingName' is used, search on repository gave no results.

**Comment by ncannasse** [comment]
That does not seem to be part of neko code, try to ask openfl.
