### ISSUE TITLE
SO_REUSEADDR on Windows

### ISSUE THREAD

**Issue by nibb13** [HaxeFoundation/neko#93]
There is no SO_REUSEADDR on Windows builds according to https://github.com/HaxeFoundation/neko/commit/81dfd3d17fcbb8bd4e772e1759f53e3ddbb1e9e1

But it is needed for creating multiple outbound sockets on same address/port for using "hole punching" NAT traversal techniques. I've removed condition, rebuilt neko for Windows and tested it for such case - it works. Can somebody explain me what exactly means "no reuse on Windows (different behavior)." and what's wrong with this option on Windows?

**Comment by ncannasse** [comment]
On Linux, for security reason, you cannot rebind the same address just after a process terminated, so I used SO_REUSEADDR in order to bypass this. On Windows, there is not this limitation and it seems it allows to bind several sockets to the same address, even if there's already one active socket listening, which we don't want to allow by default.

**Comment by nibb13** [comment]
Got it. So, next part of code causing error on "socket3.bind..." line on Linux, but works on Windows if neko compiled with SO_REUSEADDR. That's the difference, right?

```
package;

import neko.Lib;
import sys.net.Host;
import sys.net.Socket;

class Main {
	
	static function main() {
		
		var socket1:Socket = new Socket();
		socket1.bind(new Host('0.0.0.0'), 54321);
		socket1.connect(new Host('google.com'), 80);
		
		Lib.println('Socket1: OK.');
		
		var socket2:Socket = new Socket();
		socket2.bind(new Host('0.0.0.0'), 54321);
		socket2.listen(1);
		
		Lib.println('Socket2: OK.');
		
		var socket3:Socket = new Socket();
		socket3.bind(new Host('0.0.0.0'), 54321); // <-- Here should be an error
		socket3.connect(new Host('github.com'), 80);
		
		Lib.println('Socket3: OK.');

	}
}
```

What if we emulate such behavior on Windows? Maybe by additional checks for already listening socket on this port. Is there more problems?

Having no way to use SO_REUSEADDR on Windows breaks some cross-platform socket behavior which relies on it.

**Comment by ncannasse** [comment]
Well I think we don't want by default our sockets to reuse addresses since that can cause some kind of security issue. So if you want to do that, the best is maybe to write some C code that gets compiled into a NDLL and will allow you to do that.
