### ISSUE TITLE
libs/std/math.c:191: bad compare ?

### ISSUE THREAD

**Issue by dcb314** [HaxeFoundation/neko#95]
libs/std/math.c:191:36: warning: ordered comparison of pointer with integer zero [-Wextra]

   return alloc_best_int( (int)((n < 0) ? ceil(v) : floor(v)) );

**Comment by muzammalali** [comment]
Data-type of 'n' is "struct _value*". Which is a pointer to struct _value instance.

Pointer is supposed to be unsigned so (Pointer < 0) doesn't make sense

**Comment by dcb314** [comment]
>Pointer is supposed to be unsigned so (Pointer < 0) doesn't make sense

False. Pointer isn't unsigned, or signed. 

Either it points at something, or it equals 0.

Both > 0 and < 0 make no sense on pointers. Only == 0.
Hence the warning message.
