### ISSUE TITLE
nekotools boot test.n -- error, reserved name?

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/neko#96]
When first testing `nekotools boot`, I used a quick test program:

```
>echo "package; class Test { static public function main():Void { trace('Hello world'); } }" > Test.hx
>haxe -main Test.hx -neko test.n
>neko test.n
Test.hx:1: Hello world
```
All well and good, then:
```
>nekotools boot test.n
Called from tools/Tools.nml line 46
Called from core/Args.nml line 62
Called from tools/nekoboot.neko line 91
Exception : (file_open, test)
```
What? It took a while to find:
```
>mv test.n foo.n
>nekotools boot foo.n 
[no error]
>./foo
Test.hx:1: Hello world
```
Somehow if the program is `test.n`, it errors. Is test.n a reserved name? How odd!

**Comment by ibilon** [comment]
There's a `test.n` file next to neko so you can do:
```
> neko test
The virtual machine is working !
Calling a function inside std library...
Test successful
```

Maybe that create a name clash?

**Comment by mwgamera** [comment]
It's not opening `test.n` what's failing, but the output file `test`.
Sadly, the exception doesn't tell why, but what failed is probably the underlying `fopen(3)` call. Maybe `test` exists and is read-only or perhaps it is a circular link, or maybe a directory. The name itself shouldn't be reserved in any way.

**Comment by jcward** [comment]
@mwgamera - what do you know, it's an existing directory in both places I tried it. Irritating. :) Thanks for the suggestion.

**Comment by jcward** [comment]
It also fails on a non-writable file. I suppose it _could_ test for a writable output and give a sane error message, but meh.

**Comment by thomasuster** [comment]
Do you know where the source is for this? I'm down to help jcward if we combine our knowledge! (I've never touched this repo)

**Comment by jcward** [comment]
Looks like the error is thrown from here: https://github.com/HaxeFoundation/neko/blob/master/src/tools/nekoboot.neko#L92

I don't know the neko language, but presumably one could try/catch around this...

**Comment by mwgamera** [comment]
Something along the lines of:
```
var out = try
    file_open(out_name,"wb")
  catch e
    $throw("Couldn't open "+out_name+" for writing");
```
would result in your error looking like that:
```
Called from tools/Tools.nml line 46
Called from core/Args.nml line 62
Called from tools/nekoboot.neko line 92
Exception : Neko_error(Couldn't open test for writing)
```
The actual reason of failure is not exposed by std library, afaik; [std@file_open](//github.com/HaxeFoundation/neko/blob/master/libs/std/file.c#L68) just throws `$array("file_open", filename)`. One could perhaps add `strerror(errno)` somewhere in there, but I'm not sure about the implications of doing so for other code.

**Comment by jcward** [comment]
Awesome! I tend to think stack traces are ugly, so I'd personally prefer `Error: cannot write file <out_name>` and exit. I wouldn't rethrow in a commandline tool, but I suppose that's up to the maintainers.
