### ISSUE TITLE
question: what is nekoml.std?

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/neko#97]
The neko vm seems to work pretty well even with nekoml.std is not present. Is that something used by nekoc or something?

**Comment by ncannasse** [comment]
It's the nekoml standard library, it's used to compile nekoc and nekoml compilers, but not used at runtime.

**Comment by andyli** [comment]
So, should it be removed from the release? e.g. https://github.com/HaxeFoundation/neko/blob/master/bin/release.neko#L30-L39

**Comment by ncannasse** [comment]
Not if we ship nekoml compiler
